Externalizing Environment Settings
FritzAndFriends/StreamDeckEmulator pull request #7
Opened 2019-01-28 20:52 UTC by NotMyself

The current implementation uses a config file with hard-coded values. This PR adds a dependency on `dotenv` to allow the use of environment variables to pass these configuration options at runtime. For ease of use, it also will pull in any values found in a `.env` file.

I also updated the README to include getting started section.

2019-01-28 21:27 UTC, hugodahl commented on README.md
> +A simple emulator for the Stream Deck Application to allow plugin developers to develop, test, and debug their plugins without requiring a physical [Stream Deck][https://www.elgato.com/en/gaming/stre
I may have mis-edited that, but the second set of square brackets should be empty since there is a  `[Stream Deck]` reference link at the bottom. So it should look like `[Stream Deck][]`

2019-01-28 21:30 UTC, hugodahl requested changes

2019-01-28 21:30 UTC, hugodahl commented on README.md
> +A simple emulator for the Stream Deck Application to allow plugin developers to develop, test, and debug their plugins without requiring a physical [Stream Deck][https://www.elgato.com/en/gaming/stre
Apparently, I'm still "newb" enough at the GitHub process, I saw that I can apparently actually suggest changes in code, and not just type them up in comments. Will try that here with regards to my previous comment.

edit: ...or maybe not. Apologies for the comment/review spam.

2019-01-28 21:31 UTC, NotMyself commented on README.md
> +A simple emulator for the Stream Deck Application to allow plugin developers to develop, test, and debug their plugins without requiring a physical [Stream Deck][https://www.elgato.com/en/gaming/stre
Interesting, I have not used links formatted like that before. TIL.

2019-01-31 02:57 UTC, derekforeman commented
If we are going to support .env, I'd advocate for supporting both, the config (for the person who just wants to edit and run) and the .env. Changing the code to use a ternary for those bits that are supported in the .env would then be my suggestion.

2019-01-31 15:17 UTC, NotMyself commented
I hear what you are saying @derekforeman, the catch is these values are environment specific. We cannot have sensible defaults for these values:

```
BUILD_PATH=C:\\SourceCode\\Fritz\\StreamDeckToolkit\\src\\SamplePlugin\\bin\\Debug\\netcoreapp2.2\\win10-x64
WINEXE_NAME=SamplePlugin.exe
OSXEXE_NAME=SamplePlugin
```

Build path is very dependant on where the user chooses to store their source code. Executable name is also dependent on what the user does.

These values could possibly have default values:

```
DEVICE_ID=55F16B35884A859CCE4FFA1FC8D3DE5B
DEVICE_PORT=3000
```

I think device id is device specific but I am not sure. Port could be changed, but a default of 3k is probably ok. Maybe move them back to being defaults that are overridable via .env?

2019-01-31 16:23 UTC, merged

2019-01-31 16:23 UTC, csharpfritz commented
Great update, this makes it easier  to get started and configure the emulator!